# Generated by Django 6.0.6 on 2026-07-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='added_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='core.company'),
        ),
    ]
