# Generated by Django 6.0.6 on 2026-07-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_telegramuser_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.company'),
        ),
    ]
