# Generated by Django 6.0.6 on 2026-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_telegramgroup_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_add_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
