# Generated by Django 6.0.6 on 2026-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_daily_add_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
