# Generated by Django 6.0.6 on 2026-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        migrations.AlterModelTable(
            name='telegramgroup',
            table='telegram_groups',
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegram_users',
        ),
    ]
